In [1]:
import numpy as np

#create array with numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
#2d array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [3]:
arr2=np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [4]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy vectorized operation

In [7]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print("Add:", arr1+arr2)

#element wise sub
print("sub:", arr1-arr2)

#element multiplication
print("mul:", arr1*arr2)

#element division
print("div:", arr1/arr2)


Add: [11 22 33 44 55]
sub: [ -9 -18 -27 -36 -45]
mul: [ 10  40  90 160 250]
div: [0.1 0.1 0.1 0.1 0.1]


In [8]:
#universal function
arr=np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [9]:
#array slicing and indexing
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr[0][0]

np.int64(1)

In [21]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
#modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [24]:
#statistical concepts--normalization
#to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
normalized_data = (data-mean)/std_dev

print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
print("Normalized Data:", normalized_data)


Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
#logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10,-1])

data[(data>5) & (data<=8)]

array([6, 7, 8])